### PR TITLE
Changed `depends` in library.properties to exactly match package.json

### PR DESCRIPTION
**Pull request by ThomasKeil**
This adds some more libraries and fixes some "Warning! More than one package has been found by MQTT requirements:" warnings with platform.io

Tested with current platform.io 
```sh
$ pio pkg install -f 
[....]
Library Manager: Installing file:///home/******/BresserWeatherSensorReceiver
Library Manager: BresserWeatherSensorReceiver@0.28.10 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing jgromes/RadioLib#semver:^7.1.0
Library Manager: Installing thesolarnomad/lora-serialization#semver:^3.3.1
Library Manager: Installing 256dpi/arduino-mqtt#semver:^2.5.2
Library Manager: Installing bblanchon/ArduinoJson#semver:^7.2.0
Library Manager: Installing tzapu/WiFiManager#semver:2.0.17
Library Manager: Installing khoih-prog/ESP_DoubleResetDetector#semver:1.3.2
Library Manager: Installing vshymanskyy/Preferences#semver:^2.1.0
```

I tried to test this with the Arduino IDE, but couldn't figure out how to convince it to use my "private" library to trigger the dependency management.

### CODE REVIEW

**Comment by matthias-bs** [comment]
@ThomasKeil Hi, could you please provide the branch again to allow me to merge the PR?

**Review by matthias-bs — COMMENTED** [review]
O.k.

**Comment by ThomasKeil** [comment]
@matthias-bs 
My apologies, I deleted the branch since I had further problems with those libraries, which unfortunately didn't improve my situation with platform.io and potentially introduced more with Arduino IDE.

But in any case, here the branch is back, feel free to reject it if it breaks Arduino IDE building.

**Comment by matthias-bs** [comment]
@ThomasKeil 
According to https://arduino.github.io/arduino-cli/1.1/library-specification/, the version specification has a syntax like
`depends=ArduinoHttpClient (>=1.0.0)`.
Maybe that resolves the issues you encountered?

**Comment by matthias-bs** [comment]
Implemented in https://github.com/matthias-bs/BresserWeatherSensorReceiver/pull/214 with modified syntax.

**Pull request closed without merging**
